# Generated by Django 5.2.1 on 2026-01-27 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('glb', models.FileField(blank=True, null=True, upload_to='ar/')),
                ('usdz', models.FileField(blank=True, null=True, upload_to='ar/')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='ar/posters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='รูปโปรไฟล์')),
                ('role', models.CharField(choices=[('member', 'Member'), ('speaker', 'Speaker'), ('admin', 'Admin')], default='member', max_length=20, verbose_name='สิทธิ์การใช้งาน')),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='หัวข้อคำถาม')),
                ('option_a', models.CharField(max_length=200, verbose_name='ตัวเลือก A')),
                ('option_b', models.CharField(max_length=200, verbose_name='ตัวเลือก B')),
                ('option_c', models.CharField(max_length=200, verbose_name='ตัวเลือก C')),
                ('option_d', models.CharField(max_length=200, verbose_name='ตัวเลือก D')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้ทำแบบประเมิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SilkPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Si_ID', models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True)),
                ('Si_name', models.CharField(max_length=50)),
                ('Si_add', models.CharField(blank=True, max_length=50)),
                ('Si_type', models.CharField(blank=True, max_length=50)),
                ('Si_color', models.CharField(blank=True, max_length=50)),
                ('Si_source', models.TextField(blank=True)),
                ('Si_Weaving', models.CharField(blank=True, max_length=50)),
                ('reference', models.ImageField(blank=True, null=True, upload_to='ar_markers/')),
                ('target_index', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('model_3d', models.FileField(blank=True, null=True, upload_to='ar_models/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='silk_images/')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['target_index'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อกิจกรรม')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มกิจกรรม')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดกิจกรรม')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุด')),
                ('duration', models.CharField(blank=True, help_text='เช่น 6 เดือน หรือ 1 ปี', max_length=50, verbose_name='ระยะเวลา')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='สถานที่')),
                ('max_participants', models.IntegerField(default=20, verbose_name='รับจำนวนจำกัด')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดให้จอง')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workshops/', verbose_name='รูปภาพ')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Re_date', models.DateField(blank=True, null=True)),
                ('Re_quantity', models.IntegerField(default=1)),
                ('Re_status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20)),
                ('fullname', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('people', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_comment', models.TextField(blank=True)),
                ('rated_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Us_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_bookings', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.workshop', verbose_name='กิจกรรม')),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-Re_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MuseumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='National Silk Museum', max_length=255, verbose_name='ชื่อพิพิธภัณฑ์')),
                ('history', models.TextField(blank=True, null=True, verbose_name='ประวัติความเป็นมา')),
                ('biography', models.TextField(blank=True, verbose_name='คำแนะนำสั้นๆ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล')),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True, verbose_name='เวลาทำการ')),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าเข้าชม')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='ละติจูด')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='ลองจิจูด')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_type', models.CharField(choices=[('visit', 'เข้าชมพิพิธภัณฑ์'), ('workshop', 'เวิร์กช็อป')], max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='main.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SilkPatternRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(choices=[('school', 'โรงเรียน'), ('university', 'มหาวิทยาลัย'), ('tour_group', 'ทัวร์'), ('family', 'ครอบครัว'), ('organization', 'องค์กร'), ('other', 'อื่นๆ')], default='other', max_length=20)),
                ('q1_display', models.PositiveSmallIntegerField(default=3)),
                ('q2_knowledge', models.PositiveSmallIntegerField(default=3)),
                ('q3_quality', models.PositiveSmallIntegerField(default=3)),
                ('q4_variety', models.PositiveSmallIntegerField(default=3)),
                ('q5_colors', models.PositiveSmallIntegerField(default=3)),
                ('q6_ar_experience', models.PositiveSmallIntegerField(default=3)),
                ('q7_guide', models.PositiveSmallIntegerField(default=3)),
                ('q8_facility', models.PositiveSmallIntegerField(default=3)),
                ('q9_price', models.PositiveSmallIntegerField(default=3)),
                ('q10_recommend', models.PositiveSmallIntegerField(default=3)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silk_ratings', to='main.booking')),
                ('silk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='main.silkpattern')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='speaker/')),
                ('biography', models.TextField(blank=True)),
                ('expertise', models.CharField(blank=True, max_length=255, verbose_name='ความเชี่ยวชาญ')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_assignment', to='main.booking')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_items', to='main.booking')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_bookings', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.workshop')),
            ],
        ),
    ]
