# Generated by Django 5.2.1 on 2026-01-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='silkpattern',
            options={'ordering': ['target_index'], 'verbose_name': 'ข้อมูลผ้าไหม', 'verbose_name_plural': 'จัดการข้อมูลผ้าไหม'},
        ),
        migrations.RemoveField(
            model_name='museumprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='museumprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='museumprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='museumprofile',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='silkpattern',
            name='Si_Weaving',
        ),
        migrations.RemoveField(
            model_name='silkpattern',
            name='Si_add',
        ),
        migrations.RemoveField(
            model_name='silkpattern',
            name='Si_source',
        ),
        migrations.RemoveField(
            model_name='silkpattern',
            name='description',
        ),
        migrations.AddField(
            model_name='silkpattern',
            name='Si_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='แหล่งผลิตผ้าไหม'),
        ),
        migrations.AddField(
            model_name='silkpattern',
            name='Si_history',
            field=models.TextField(blank=True, verbose_name='ประวัติลายผ้า'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_ID',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, verbose_name='รหัสผ้า'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='สีของผ้า'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_name',
            field=models.CharField(max_length=50, verbose_name='ชื่อลายผ้า'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='ชนิดของผ้า'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='silk_images/', verbose_name='รูปภาพประกอบ'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='ar_models/', verbose_name='โมเดล 3 มิติ'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='reference',
            field=models.ImageField(blank=True, null=True, upload_to='ar_markers/', verbose_name='รูปภาพอ้างอิง AR'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='target_index',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ลำดับเป้าหมาย (Index)'),
        ),
    ]
