# Generated by Django 5.2.1 on 2026-01-28 08:30

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_silkpattern_options_remove_museumprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakerassignment',
            name='id',
        ),
        migrations.AddField(
            model_name='speakerassignment',
            name='assignment_id',
            field=models.CharField(blank=True, default=main.models.generate_assignment_id, max_length=13, primary_key=True, serialize=False, verbose_name='รหัสมอบหมายวิทยากร'),
        ),
        migrations.AddField(
            model_name='speakerassignment',
            name='quantity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='จำนวน'),
        ),
        migrations.AddField(
            model_name='speakerassignment',
            name='schedule_text',
            field=models.TextField(blank=True, null=True, verbose_name='วันที่-เวลา'),
        ),
        migrations.AlterField(
            model_name='speakerassignment',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker_assignment', to='main.booking', verbose_name='การจอง/กิจกรรม'),
        ),
        migrations.AlterField(
            model_name='speakerassignment',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='main.speaker', verbose_name='วิทยากร'),
        ),
        migrations.AlterField(
            model_name='speakerassignment',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='speakerassignment',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='หัวข้อ'),
        ),
    ]
