# Generated by Django 5.2.1 on 2026-01-29 07:44

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_speakerassignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerassignment',
            name='assignment_id',
            field=models.CharField(blank=True, default=main.models.generate_assignment_id, editable=False, max_length=13, primary_key=True, serialize=False, verbose_name='รหัสมอบหมายวิทยากร'),
        ),
    ]
