# Generated by Django 5.2.1 on 2026-01-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_booking_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('case_type', models.CharField(choices=[('living_pattern', 'ลายผ้ามีชีวิต (Living Pattern)'), ('try_on', 'จำลองการสวมใส่ (Virtual Try-On)'), ('legend', 'ตำนานความเชื่อ (Legend/Story)'), ('education', 'อุปกรณ์/กี่ทอผ้า (Education)'), ('lifecycle', 'วงจรชีวิตไหม (Life Cycle)')], max_length=20)),
                ('glb_file', models.FileField(upload_to='ar_showcase/glb/')),
                ('usdz_file', models.FileField(blank=True, null=True, upload_to='ar_showcase/usdz/')),
                ('cover_image', models.ImageField(upload_to='ar_showcase/covers/')),
                ('target_index', models.IntegerField(unique=True)),
            ],
        ),
    ]
