# Generated by Django 5.2.1 on 2026-02-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_arshowcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ARShowcase',
        ),
        migrations.AlterModelOptions(
            name='silkpattern',
            options={'ordering': ['target_index'], 'verbose_name': 'ข้อมูลลายผ้าไหม', 'verbose_name_plural': 'จัดการลายผ้าไหม (AR & Info)'},
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_ID',
            field=models.CharField(blank=True, db_index=True, max_length=13, null=True, unique=True, verbose_name='รหัสผ้า (Si_ID)'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='แหล่งผลิต/ที่มา'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='สีหลัก'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_history',
            field=models.TextField(blank=True, verbose_name='ประวัติและความเป็นมา'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_name',
            field=models.CharField(max_length=100, verbose_name='ชื่อลายผ้า'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='Si_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='ประเภทผ้า'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/images/', verbose_name='รูปภาพประกอบลายผ้า'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='main/models/', verbose_name='ไฟล์โมเดล 3 มิติ (.glb)'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='reference',
            field=models.ImageField(blank=True, null=True, upload_to='main/targets/', verbose_name='รูปภาพอ้างอิง AR (Reference Image)'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='target_index',
            field=models.PositiveIntegerField(blank=True, help_text='ระบุตัวเลขลำดับ (เริ่มจาก 0) ที่สอดคล้องกับตำแหน่งรูปภาพในไฟล์ .mind', null=True, unique=True, verbose_name='ลำดับเป้าหมายในไฟล์ .mind (Target Index)'),
        ),
    ]
