# Generated by Django 5.2.1 on 2026-02-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_arshowcase_alter_silkpattern_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silkpattern',
            name='target_index',
            field=models.PositiveIntegerField(blank=True, help_text='ใส่เลข 0, 1, 2... ให้ตรงกับลำดับรูปที่ใช้ทำไฟล์ .mind', null=True, unique=True, verbose_name='ลำดับเป้าหมายในไฟล์ .mind (Target Index)'),
        ),
    ]
