# Generated by Django 5.2.1 on 2026-02-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_surveyrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_e',
            field=models.CharField(blank=True, default='5', max_length=200, verbose_name='ตัวเลือก E'),
        ),
    ]
