# Generated by Django 5.2.1 on 2026-02-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_question_option_e'),
    ]

    operations = [
        migrations.AddField(
            model_name='silkpattern',
            name='target_file',
            field=models.CharField(blank=True, help_text='ระบุชื่อไฟล์ .mind ที่ประกอบด้วยรูปของรายการนี้ (ว่างได้)', max_length=100, null=True, verbose_name='ชื่อไฟล์ .mind ที่เก็บรูป (เช่น targets0.mind)'),
        ),
    ]
