# Generated by Django 5.2.1 on 2026-02-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_silkpattern_target_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='silkpattern',
            name='mannequin_model_3d',
            field=models.FileField(blank=True, null=True, upload_to='main/models/', verbose_name='โมเดลหุ่น (.glb)'),
        ),
        migrations.AddField(
            model_name='silkpattern',
            name='silk_model_3d',
            field=models.FileField(blank=True, null=True, upload_to='main/models/', verbose_name='โมเดลผ้า (.glb)'),
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='main/models/', verbose_name='ไฟล์โมเดล 3 มิติ (.glb) (เก่า)'),
        ),
    ]
