# Generated by Django 5.2.1 on 2026-02-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_silkpattern_mannequin_model_3d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมลทางการ'),
        ),
        migrations.AddField(
            model_name='museumprofile',
            name='gallery_image1',
            field=models.ImageField(blank=True, null=True, upload_to='main/museum/', verbose_name='รูปแกลเลอรี 1 (เกี่ยวกับพิพิธภัณฑ์)'),
        ),
        migrations.AddField(
            model_name='museumprofile',
            name='gallery_image2',
            field=models.ImageField(blank=True, null=True, upload_to='main/museum/', verbose_name='รูปแกลเลอรี 2 (เกี่ยวกับพิพิธภัณฑ์)'),
        ),
        migrations.AddField(
            model_name='museumprofile',
            name='gallery_image3',
            field=models.ImageField(blank=True, null=True, upload_to='main/museum/', verbose_name='รูปแกลเลอรี 3 (เกี่ยวกับพิพิธภัณฑ์)'),
        ),
        migrations.AddField(
            model_name='museumprofile',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='ใช้แสดงเป็นภาพพื้นหลัง/เฮดเดอร์บนหน้าแรกของเว็บไซต์', null=True, upload_to='main/museum/', verbose_name='รูปพื้นหลังหลักของหน้าแรก'),
        ),
    ]
