# Generated by Django 5.2.1 on 2026-02-18 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_museumprofile_email_museumprofile_gallery_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visit_session',
            field=models.CharField(blank=True, choices=[('morning', 'ช่วงเช้า (09:00-12:00)'), ('afternoon', 'ช่วงบ่าย (13:00-16:00)')], max_length=20, null=True, verbose_name='ช่วงเวลาเข้าชม'),
        ),
    ]
