# Generated by Django 5.2.1 on 2026-02-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_booking_visit_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='inactive_reason',
            field=models.CharField(blank=True, help_text='เช่น วัสดุอุปกรณ์ไม่พอ / เต็มแล้ว / ปิดปรับปรุง', max_length=255, verbose_name='เหตุผลที่ปิดกิจกรรม'),
        ),
    ]
