# Generated by Django 6.0.1 on 2026-02-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_workshop_inactive_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='session_period',
            field=models.CharField(blank=True, choices=[('morning', 'ช่วงเช้า'), ('afternoon', 'ช่วงบ่าย'), ('both', 'ทั้งเช้าและบ่าย')], default='both', help_text='เลือกช่วงเวลาที่จัดกิจกรรม (เช้า / บ่าย / ทั้งเช้าและบ่าย)', max_length=20, verbose_name='ช่วงจัดกิจกรรม'),
        ),
    ]
