# Generated by Django 6.0.1 on 2026-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_workshop_session_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='detail_image',
            field=models.ImageField(blank=True, help_text='รูปเพิ่มเติมที่ใช้แสดงในหน้ารายละเอียดกิจกรรม', null=True, upload_to='workshops/', verbose_name='รูปประกอบกิจกรรม'),
        ),
    ]
