# Generated by Django 6.0.1 on 2026-02-21 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_workshop_detail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workshops/gallery/', verbose_name='รูปประกอบกิจกรรมเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.workshop', verbose_name='กิจกรรม')),
            ],
            options={
                'verbose_name': 'รูปประกอบกิจกรรม',
                'verbose_name_plural': 'รูปประกอบกิจกรรม (หลายรูปต่อกิจกรรม)',
            },
        ),
    ]
