# Generated by Django 6.0.1 on 2026-02-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_workshopgalleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silkpattern',
            name='target_index',
            field=models.PositiveIntegerField(blank=True, help_text='ใส่เลข 0, 1, 2... ให้ตรงกับลำดับรูปที่ใช้ทำไฟล์ .mind', null=True, verbose_name='ลำดับเป้าหมายในไฟล์ .mind (Target Index)'),
        ),
        migrations.AlterUniqueTogether(
            name='silkpattern',
            unique_together={('target_file', 'target_index')},
        ),
    ]
