# Generated by Django 6.0.1 on 2026-02-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_silkpattern_target_index_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booking',
            table='main_booking',
        ),
    ]
