# Generated by Django 6.0.1 on 2026-02-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_booking_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silkpattern',
            name='mannequin_model_3d',
        ),
        migrations.RemoveField(
            model_name='silkpattern',
            name='silk_model_3d',
        ),
        migrations.AlterField(
            model_name='silkpattern',
            name='model_3d',
            field=models.FileField(blank=True, null=True, upload_to='main/models/', verbose_name='โมเดล 3D (.glb)'),
        ),
    ]
