# Generated by Django 6.0.1 on 2026-02-25 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_silkpattern_mannequin_model_3d_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilkPatternGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main/gallery_images/', verbose_name='รูปประกอบผ้าเพิ่มเติม')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('silkpattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.silkpattern', verbose_name='ลายผ้า')),
            ],
            options={
                'verbose_name': 'รูปประกอบผ้าเพิ่มเติม',
                'verbose_name_plural': 'รูปประกอบผ้าเพิ่มเติมทั้งหมด',
            },
        ),
    ]
