# Generated by Django 6.0.1 on 2026-02-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_silkpatterngalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาที่ยกเลิก'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Re_status',
            field=models.CharField(choices=[('pending', 'รออนุมัติการจอง'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิกโดยผู้ใช้')], default='pending', max_length=20),
        ),
    ]
