# Generated by Django 6.0.1 on 2026-02-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_booking_cancel_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Re_status',
            field=models.CharField(choices=[('pending', 'รออนุมัติการจอง'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('cancelled', 'ยกเลิกโดยผู้ใช้'), ('confirmed', 'มอบหมายวิทยากรแล้ว'), ('completed', 'เสร็จสิ้นการเข้าชม')], default='pending', max_length=20),
        ),
    ]
