# Generated by Django 6.0.1 on 2026-02-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_booking_re_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerWorkUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='หัวข้อ/ชื่อชุดรูป')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ/รายละเอียด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_uploads', to='main.speakerassignment', verbose_name='งานที่รับผิดชอบ')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_uploads', to='main.speaker', verbose_name='วิทยากร')),
            ],
            options={
                'verbose_name': 'ชุดรูปผลงานวิทยากร',
                'verbose_name_plural': 'ชุดรูปผลงานวิทยากร',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpeakerWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='speaker/work/', verbose_name='รูปภาพ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.speakerworkupload', verbose_name='ชุดอัปโหลด')),
            ],
            options={
                'verbose_name': 'รูปผลงานวิทยากร',
                'verbose_name_plural': 'รูปผลงานวิทยากร',
                'ordering': ['-created_at'],
            },
        ),
    ]
