# Generated by Django on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_speakerworkupload_speakerworkimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="speakerassignment",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
