# Generated by Django 6.0.1 on 2026-03-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_speakerassignment_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='museumprofile',
            name='logo',
            field=models.ImageField(blank=True, help_text='ใช้แสดงเป็นโลโก้ของพิพิธภัณฑ์ในหน้ารายงาน/ส่วนหัวต่าง ๆ', null=True, upload_to='main/museum/', verbose_name='โลโก้พิพิธภัณฑ์'),
        ),
    ]
