# Generated by Django 5.2.1 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_museumprofile_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingquestionresponse",
            name="submission_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
