# Generated by Django 6.0.1 on 2026-03-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_question_category_alter_arasset_glb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='silkpattern',
            name='Si_assistant_artists',
            field=models.TextField(blank=True, default='', help_text='หากมีหลายคน สามารถพิมพ์คั่นด้วยเครื่องหมายจุลภาค หรือขึ้นบรรทัดใหม่', verbose_name='ศิลปินผู้ช่วย (ผู้ช่วยสร้างสรรค์งาน)'),
        ),
        migrations.AddField(
            model_name='silkpattern',
            name='Si_contact_phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='เบอร์โทรสำหรับติดต่อ'),
        ),
        migrations.AddField(
            model_name='silkpattern',
            name='Si_main_artist',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ศิลปินหลัก (เจ้าของวัตถุ)'),
        ),
    ]
